"""initial tables

Revision ID: edb5d264099c
Revises: 
Create Date: 2026-05-03 10:07:11.907614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb5d264099c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('affected_services', sa.Text(), nullable=True),
    sa.Column('downstream_services', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('orchestrator_plan', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('healing_report', sa.Text(), nullable=True),
    sa.Column('generated_files', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployment_service_status', 'deployments', ['service_name', 'status'], unique=False)
    op.create_index('ix_deployment_status_created', 'deployments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_service_name'), 'deployments', ['service_name'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_service_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index('ix_deployment_status_created', table_name='deployments')
    op.drop_index('ix_deployment_service_status', table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
